# Generated by Django 5.2.5 on 2025-11-06 07:17

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('codigo', models.CharField(default='SINCODIGO', max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'facultad',
            },
        ),
        migrations.CreateModel(
            name='MotivoAusencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'motivo_ausencia',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_institucional', models.EmailField(max_length=255, unique=True)),
                ('telefono_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_oficina', models.CharField(blank=True, max_length=20, null=True)),
                ('cif_identificacion', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[\\w-]+$', 'Formato inválido para CIF')])),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('COORDINADOR', 'Coordinador'), ('SECRETARIA', 'Secretaría'), ('ADMIN', 'Administrador')], default='ESTUDIANTE', max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_almacenamiento', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=128, null=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('encriptado', models.BooleanField(default=False)),
                ('estado', models.CharField(default='DISPONIBLE', max_length=30)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='core.facultad')),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas', to=settings.AUTH_USER_MODEL)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas', to='core.facultad')),
            ],
            options={
                'db_table': 'asignatura',
            },
        ),
        migrations.CreateModel(
            name='HistorialAccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_accion', models.CharField(max_length=100)),
                ('descripcion_accion', models.TextField(blank=True, null=True)),
                ('referencia_id', models.UUIDField(blank=True, null=True)),
                ('fecha_accion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_accion',
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_ausencia_inicio', models.DateField()),
                ('fecha_ausencia_fin', models.DateField()),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion_detallada', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], default='PENDIENTE', max_length=30)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivo_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivo_principal_de', to='core.documento')),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones', to='core.asignatura')),
                ('estudiante', models.ForeignKey(limit_choices_to={'role': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='justificaciones', to=settings.AUTH_USER_MODEL)),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.motivoausencia')),
            ],
            options={
                'db_table': 'justificacion',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='justificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.justificacion'),
        ),
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol_revisor', models.CharField(choices=[('COORDINADOR', 'Coordinador'), ('DOCENTE', 'Docente')], max_length=30)),
                ('fecha_revision', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], max_length=30)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('justificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='core.justificacion')),
            ],
            options={
                'db_table': 'aprobacion',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['cif_identificacion'], name='idx_users_cif'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_users_role'),
        ),
        migrations.AddIndex(
            model_name='historialaccion',
            index=models.Index(fields=['usuario'], name='idx_historial_usuario'),
        ),
        migrations.AddIndex(
            model_name='aprobacion',
            index=models.Index(fields=['justificacion'], name='idx_aprob_justificacion'),
        ),
        migrations.AddIndex(
            model_name='justificacion',
            index=models.Index(fields=['estudiante'], name='idx_justificacion_estudiante'),
        ),
        migrations.AddIndex(
            model_name='justificacion',
            index=models.Index(fields=['estado'], name='idx_justificacion_estado'),
        ),
        migrations.AddIndex(
            model_name='justificacion',
            index=models.Index(fields=['fecha_solicitud'], name='idx_justificacion_f_solicitud'),
        ),
        migrations.AddConstraint(
            model_name='justificacion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_ausencia_fin__gte', models.F('fecha_ausencia_inicio'))), name='chk_fecha_ausencia'),
        ),
    ]
