# Generated by Django 5.2.5 on 2025-11-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='codigo',
            field=models.CharField(default='SINCODIGO', max_length=20),
        ),
    ]
