# Generated by Django 5.2.5 on 2025-11-03 07:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_facultad_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivoausencia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
